name: Publish KDocs
on:
  push:
    branches:
      - master
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./gradlew dokkaHtmlMultiModule
      - name: Publish KDocs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule
          publish_branch: kdocs
